# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 35fc4a65f16122294902096e2949c0460037f0c5f337f07008dea0fc2e4931ba96ab59b00c229816cabb989af944fde41bc86e2817422efde0897d8d5e9cf466

test:
  secret_key_base: a71fac0e2d278fd7772a633606188635076bf6cec0b39838d8b7d975a65c24b24fa16f07769b3ec741f965ce3eb715f70e3e28fdb8de4078cb1eff0ed48a6aac

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
